### ISSUE TITLE
有没有考虑增加 IPv4 地址分流的功能？

### ISSUE THREAD

**Issue by bazingaterry** [holyshawn/ballade#1]
我的想法是这样顺序进行分流：

1. 如果有 IPv6 地址，直连。
2. 是否匹配 SwitchyOmega 中的规则。
3. 最后，国内 IP 地址直连，否则走代理。

**Comment by holyshawn** [comment]
第三个顺序如果用IP的话就好考虑DNS污染以及DNS分布式解析的问题，不如用域名解决。如果用域名的话，那你可以直接使用gfwlist转换到SwitchyOmega，SwitchyOmega有帮助教程：
https://github.com/FelisCatus/SwitchyOmega/wiki/gfwlist

**Comment by holyshawn** [comment]
@bazingaterry 添加了按照你所说的规则的分流功能，可以试试看。
要升级到最新的0.97版本，配置文件有一定的更改，最好把原先的配置文件夹删除重新配置一下。

**Comment by bazingaterry** [comment]
@holyshawn 使用了一天，暂时没有遇到什么问题，感谢采纳！
